Repository Tavern-Keeper-2308/tavern_keeper_be, pull requests merged in 2024-02, with the labels that each got.

#21 Database creation, and Gemfile configuration
  .gitignore
  .rspec
  Gemfile
  Gemfile.lock
  app/models/encounter.rb
  app/models/encounter_monster.rb
  db/migrate/20240202174215_create_encounters.rb
  db/migrate/20240202174345_create_encounter_monsters.rb
  db/schema.rb
  spec/factories/encounter_monsters.rb
  spec/factories/encounters.rb
  spec/models/encounter_monster_spec.rb
  spec/models/encounter_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: test, task

#22 [BE] GraphQL Setup
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/controllers/graphql_controller.rb
  app/graphql/mutations/.keep
  app/graphql/mutations/base_mutation.rb
  app/graphql/resolvers/base_resolver.rb
  app/graphql/tavern_keeper_schema.rb
  app/graphql/types/.keep
  app/graphql/types/base_argument.rb
  app/graphql/types/base_connection.rb
  app/graphql/types/base_edge.rb
  app/graphql/types/base_enum.rb
  app/graphql/types/base_field.rb
  app/graphql/types/base_input_object.rb
  app/graphql/types/base_interface.rb
  app/graphql/types/base_object.rb
  app/graphql/types/base_scalar.rb
  app/graphql/types/base_union.rb
  app/graphql/types/encounter_monster_type.rb
  app/graphql/types/encounter_type.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/node_type.rb
  app/graphql/types/query_type.rb
  config/application.rb
  config/puma.rb
  config/routes.rb
Labels: needs review, task

#29 Write tests for monster requests
  app/graphql/types/query_type.rb
  spec/fixtures/vcr_cassettes/Queries_Monster/_/returns_monster_details.yml
  spec/fixtures/vcr_cassettes/Queries_Monsters/_/returns_all_monsters.yml
  spec/graphql/queries/requests/monster_details_spec.rb
  spec/graphql/queries/requests/monsters_index_spec.rb
Labels: test

#38 [BE] Add render build file
  bin/render-build.sh
Labels: task

#33 [BE] Query Encounters by username
  .gitignore
  app/graphql/mutations/create_encounter.rb
  app/graphql/types/encounter_type.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/query_type.rb
  app/models/encounter.rb
  db/migrate/20240206181600_add_column_to_encounters.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/encounter_monsters.rb
  spec/factories/encounters.rb
  spec/fixtures/vcr_cassettes/DndService/DndService_GrapQL_API_service_methods/_query_monster_details_index_returns_A_DIFFERENT_MONSTER.yml
  spec/fixtures/vcr_cassettes/DndService/DndService_GrapQL_API_service_methods/_query_monster_details_index_returns_monster_details_for_single_monster.yml
  spec/fixtures/vcr_cassettes/DndService/DndService_GrapQL_API_service_methods/_query_monster_list_returns_all_monsters_name_and_index_only.yml
  spec/fixtures/vcr_cassettes/MonsterFacade/MonsterFacade_instance_methods/_monster_list.yml
  spec/fixtures/vcr_cassettes/MonsterFacade/MonsterFacade_instance_methods/_single_monster_details_index_.yml
  spec/fixtures/vcr_cassettes/Queries_Monster/monster/returns_monster_details.yml
  spec/fixtures/vcr_cassettes/Queries_Monsters/monsters/returns_all_monsters.yml
  spec/graphql/queries/requests/encounters_index_spec.rb
  spec/models/encounter_spec.rb
Labels: task

#39 Circleci project setup
  .circleci/config.yml
  app/graphql/types/mutation_type.rb
Labels: task

#40 Create Encounter Mutation
  app/graphql/mutations/create_encounter.rb
  app/graphql/tavern_keeper_schema.rb
  app/graphql/types/encounter_type.rb
  app/graphql/types/monster_type.rb
  app/graphql/types/mutation_type.rb
  app/poros/monster.rb
  config/routes.rb
  spec/facades/monster_facade_spec.rb
  spec/graphql/mutations/requests/create_encounter_spec.rb
  spec/graphql/queries/requests/monster_details_spec.rb
  spec/graphql/queries/requests/monsters_index_spec.rb
Labels: task

#42 Single Encounter Details
  app/graphql/types/encounter_monster_type.rb
  app/graphql/types/query_type.rb
  spec/graphql/queries/requests/encounter_details_spec.rb
Labels: task

#45 Fix - Add EncounterMonster Index to Create Encounter Mutation
  app/graphql/mutations/create_encounter.rb
  spec/graphql/mutations/requests/create_encounter_spec.rb
Labels: task

#47 Change armor_class Data Type to Integer
  app/graphql/types/monster_type.rb
  app/poros/monster.rb
  spec/facades/monster_facade_spec.rb
  spec/graphql/queries/requests/monster_details_spec.rb
  spec/poros/monster_spec.rb
Labels: task

#43 add cleanup phase to seeds
  db/seeds.rb
Labels: bug

#1 Start README skeleton
  .DS_Store
  .gitignore
  README.md
  images/logo.png
  images/schema.png
Labels: documentation
